using HiQoDataGenerator.DAL.Models.DataSetModels;
using Microsoft.EntityFrameworkCore;

namespace HiQoDataGenerator.DAL.Extensions
{
    public static class DogBreedsSeeds
    {
        public static void SeedDogBreeds(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DefinedDatasetValue>()
                .HasData(
                    new DefinedDatasetValue { Id = 757, Value = "ENGLISH POINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 758, Value = "ENGLISH SETTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 759, Value = "KERRY BLUE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 760, Value = "CAIRN TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 761, Value = "ENGLISH COCKER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 762, Value = "GORDON SETTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 763, Value = "AIREDALE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 764, Value = "AUSTRALIAN TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 765, Value = "BEDLINGTON TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 766, Value = "BORDER TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 767, Value = "BULL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 768, Value = "FOX TERRIER (SMOOTH)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 769, Value = "ENGLISH TOY TERRIER (BLACK &TAN)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 770, Value = "SWEDISH VALLHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 771, Value = "BELGIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 772, Value = "OLD ENGLISH SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 773, Value = "GRIFFON NIVERNAIS", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 774, Value = "BRIQUET GRIFFON VENDEEN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 775, Value = "ARIEGEOIS", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 776, Value = "GASCON SAINTONGEOIS", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 777, Value = "GREAT GASCONY BLUE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 778, Value = "POITEVIN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 779, Value = "BILLY", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 780, Value = "ARTOIS HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 781, Value = "PORCELAINE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 782, Value = "SMALL BLUE GASCONY", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 783, Value = "BLUE GASCONY GRIFFON", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 784, Value = "GRAND BASSET GRIFFON VENDEEN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 785, Value = "NORMAN ARTESIEN BASSET", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 786, Value = "BLUE GASCONY BASSET", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 787, Value = "BASSET FAUVE DE BRETAGNE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 788, Value = "PORTUGUESE WATER DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 789, Value = "WELSH CORGI (CARDIGAN)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 790, Value = "WELSH CORGI (PEMBROKE)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 791, Value = "IRISH SOFT COATED WHEATEN TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 792, Value = "YUGOSLAVIAN SHEPHERD DOG - SHARPLANINA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 793, Value = "JÄMTHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 794, Value = "BASENJI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 795, Value = "BERGER DE BEAUCE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 796, Value = "BERNESE MOUNTAIN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 797, Value = "APPENZELL CATTLE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 798, Value = "ENTLEBUCH CATTLE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 799, Value = "KARELIAN BEAR DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 800, Value = "FINNISH SPITZ", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 801, Value = "NEWFOUNDLAND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 802, Value = "FINNISH HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 803, Value = "POLISH HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 804, Value = "KOMONDOR", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 805, Value = "KUVASZ", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 806, Value = "PULI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 807, Value = "PUMI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 808, Value = "HUNGARIAN SHORT-HAIRED POINTER (VIZSLA)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 809, Value = "GREAT SWISS MOUNTAIN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 810, Value = "SWISS HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 811, Value = "SMALL SWISS HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 812, Value = "ST. BERNARD", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 813, Value = "COARSE-HAIRED STYRIAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 814, Value = "AUSTRIAN BLACK AND TAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 815, Value = "AUSTRIAN  PINSCHER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 816, Value = "MALTESE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 817, Value = "FAWN BRITTANY GRIFFON", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 818, Value = "PETIT BASSET GRIFFON VENDEEN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 819, Value = "TYROLEAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 820, Value = "LAKELAND TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 821, Value = "MANCHESTER TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 822, Value = "NORWICH TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 823, Value = "SCOTTISH TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 824, Value = "SEALYHAM TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 825, Value = "SKYE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 826, Value = "STAFFORDSHIRE BULL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 827, Value = "CONTINENTAL TOY SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 828, Value = "WELSH TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 829, Value = "GRIFFON BRUXELLOIS", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 830, Value = "GRIFFON BELGE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 831, Value = "PETIT BRABANÇON", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 832, Value = "SCHIPPERKE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 833, Value = "BLOODHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 834, Value = "WEST HIGHLAND WHITE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 835, Value = "YORKSHIRE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 836, Value = "CATALAN SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 837, Value = "SHETLAND SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 838, Value = "IBIZAN PODENCO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 839, Value = "BURGOS POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 840, Value = "SPANISH MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 841, Value = "PYRENEAN MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 842, Value = "PORTUGUESE SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 843, Value = "PORTUGUESE WARREN HOUND-PORTUGUESE PODENGO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 844, Value = "BRITTANY SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 845, Value = "RAFEIRO OF ALENTEJO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 846, Value = "GERMAN SPITZ", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 847, Value = "GERMAN WIRE- HAIRED POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 848, Value = "WEIMARANER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 849, Value = "WESTPHALIAN DACHSBRACKE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 850, Value = "FRENCH BULLDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 851, Value = "KLEINER MÜNSTERLÄNDER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 852, Value = "GERMAN HUNTING TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 853, Value = "GERMAN SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 854, Value = "FRENCH WATER DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 855, Value = "BLUE PICARDY SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 856, Value = "WIRE-HAIRED POINTING GRIFFON KORTHALS", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 857, Value = "PICARDY SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 858, Value = "CLUMBER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 859, Value = "CURLY COATED RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 860, Value = "GOLDEN RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 861, Value = "BRIARD", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 862, Value = "PONT-AUDEMER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 863, Value = "SAINT GERMAIN POINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 864, Value = "DOGUE DE BORDEAUX", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 865, Value = "DEUTSCH LANGHAAR", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 866, Value = "LARGE MUNSTERLANDER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 867, Value = "GERMAN SHORT- HAIRED POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 868, Value = "IRISH RED SETTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 869, Value = "FLAT COATED RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 870, Value = "LABRADOR RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 871, Value = "FIELD SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 872, Value = "IRISH WATER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 873, Value = "ENGLISH SPRINGER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 874, Value = "WELSH SPRINGER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 875, Value = "SUSSEX SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 876, Value = "KING CHARLES SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 877, Value = "SMÅLANDSSTÖVARE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 878, Value = "DREVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 879, Value = "SCHILLERSTÖVARE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 880, Value = "HAMILTONSTÖVARE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 881, Value = "FRENCH POINTING DOG - GASCOGNE TYPE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 882, Value = "FRENCH POINTING DOG - PYRENEAN TYPE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 883, Value = "SWEDISH LAPPHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 884, Value = "CAVALIER KING CHARLES SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 885, Value = "PYRENEAN MOUNTAIN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 886, Value = "PYRENEAN SHEEPDOG - SMOOTH FACED", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 887, Value = "IRISH TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 888, Value = "BOSTON TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 889, Value = "LONG-HAIRED PYRENEAN SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 890, Value = "SLOVAKIAN CHUVACH", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 891, Value = "DOBERMANN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 892, Value = "BOXER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 893, Value = "LEONBERGER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 894, Value = "RHODESIAN RIDGEBACK", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 895, Value = "ROTTWEILER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 896, Value = "DACHSHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 897, Value = "BULLDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 898, Value = "SERBIAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 899, Value = "ISTRIAN SHORT-HAIRED HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 900, Value = "ISTRIAN WIRE-HAIRED HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 901, Value = "DALMATIAN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 902, Value = "POSAVATZ HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 903, Value = "BOSNIAN BROKEN-HAIRED HOUND - CALLED BARAK", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 904, Value = "COLLIE ROUGH", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 905, Value = "BULLMASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 906, Value = "GREYHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 907, Value = "ENGLISH FOXHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 908, Value = "IRISH WOLFHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 909, Value = "BEAGLE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 910, Value = "WHIPPET", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 911, Value = "BASSET HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 912, Value = "DEERHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 913, Value = "ITALIAN SPINONE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 914, Value = "GERMAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 915, Value = "AMERICAN COCKER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 916, Value = "DANDIE DINMONT TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 917, Value = "FOX TERRIER (WIRE)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 918, Value = "CASTRO LABOREIRO DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 919, Value = "BOUVIER DES ARDENNES", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 920, Value = "POODLE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 921, Value = "ESTRELA MOUNTAIN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 922, Value = "FRENCH SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 923, Value = "PICARDY SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 924, Value = "ARIEGE POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 925, Value = "BOURBONNAIS POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 926, Value = "AUVERGNE POINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 927, Value = "GIANT SCHNAUZER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 928, Value = "SCHNAUZER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 929, Value = "MINIATURE SCHNAUZER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 930, Value = "GERMAN PINSCHER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 931, Value = "MINIATURE PINSCHER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 932, Value = "AFFENPINSCHER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 933, Value = "PORTUGUESE POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 934, Value = "SLOUGHI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 935, Value = "FINNISH LAPPONIAN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 936, Value = "HOVAWART", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 937, Value = "BOUVIER DES FLANDRES", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 938, Value = "KROMFOHRLÄNDER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 939, Value = "BORZOI - RUSSIAN HUNTING SIGHTHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 940, Value = "BERGAMASCO SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 941, Value = "ITALIAN VOLPINO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 942, Value = "BOLOGNESE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 943, Value = "NEAPOLITAN MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 944, Value = "ITALIAN ROUGH-HAIRED SEGUGIO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 945, Value = "CIRNECO DELL'ETNA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 946, Value = "ITALIAN SIGHTHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 947, Value = "MAREMMA AND THE ABRUZZES SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 948, Value = "ITALIAN POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 949, Value = "NORWEGIAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 950, Value = "SPANISH HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 951, Value = "CHOW CHOW", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 952, Value = "JAPANESE CHIN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 953, Value = "PEKINGESE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 954, Value = "SHIH TZU", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 955, Value = "TIBETAN TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 956, Value = "CANADIAN ESKIMO DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 957, Value = "SAMOYED", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 958, Value = "HANOVERIAN SCENT HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 959, Value = "HELLENIC HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 960, Value = "BICHON FRISE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 961, Value = "PUDELPOINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 962, Value = "BAVARIAN MOUNTAIN SCENT HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 963, Value = "CHIHUAHUA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 964, Value = "FRENCH TRICOLOUR HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 965, Value = "FRENCH WHITE & BLACK HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 966, Value = "FRISIAN WATER DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 967, Value = "STABIJHOUN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 968, Value = "DUTCH SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 969, Value = "DRENTSCHE PARTRIDGE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 970, Value = "FILA BRASILEIRO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 971, Value = "LANDSEER (EUROPEAN CONTINENTAL TYPE)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 972, Value = "LHASA APSO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 973, Value = "AFGHAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 974, Value = "SERBIAN TRICOLOUR HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 975, Value = "TIBETAN MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 976, Value = "TIBETAN SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 977, Value = "DEUTSCH STICHELHAAR", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 978, Value = "LITTLE LION DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 979, Value = "XOLOITZCUINTLE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 980, Value = "GREAT DANE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 981, Value = "AUSTRALIAN SILKY TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 982, Value = "NORWEGIAN BUHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 983, Value = "MUDI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 984, Value = "HUNGARIAN WIRE-HAIRED POINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 985, Value = "HUNGARIAN GREYHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 986, Value = "HUNGARIAN HOUND - TRANSYLVANIAN SCENT HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 987, Value = "NORWEGIAN ELKHOUND GREY", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 988, Value = "ALASKAN MALAMUTE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 989, Value = "SLOVAKIAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 990, Value = "BOHEMIAN WIRE-HAIRED POINTING GRIFFON", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 991, Value = "CESKY TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 992, Value = "ATLAS MOUNTAIN DOG (AIDI)", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 993, Value = "PHARAOH HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 994, Value = "MAJORCA MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 995, Value = "HAVANESE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 996, Value = "POLISH LOWLAND SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 997, Value = "TATRA SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 998, Value = "PUG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 999, Value = "ALPINE DACHSBRACKE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1000, Value = "AKITA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1001, Value = "SHIBA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1002, Value = "JAPANESE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1003, Value = "TOSA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1004, Value = "HOKKAIDO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1005, Value = "JAPANESE SPITZ", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1006, Value = "CHESAPEAKE BAY RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1007, Value = "MASTIFF", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1008, Value = "NORWEGIAN LUNDEHUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1009, Value = "HYGEN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1010, Value = "HALDEN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1011, Value = "NORWEGIAN ELKHOUND BLACK", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1012, Value = "SALUKI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1013, Value = "SIBERIAN HUSKY", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1014, Value = "BEARDED COLLIE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1015, Value = "NORFOLK TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1016, Value = "CANAAN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1017, Value = "GREENLAND DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1018, Value = "NORRBOTTENSPITZ", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1019, Value = "CROATIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1020, Value = "KARST SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1021, Value = "MONTENEGRIN MOUNTAIN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1022, Value = "OLD DANISH POINTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1023, Value = "GRAND GRIFFON VENDEEN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1024, Value = "COTON DE TULEAR", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1025, Value = "LAPPONIAN HERDER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1026, Value = "SPANISH GREYHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1027, Value = "AMERICAN STAFFORDSHIRE TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1028, Value = "AUSTRALIAN CATTLE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1029, Value = "CHINESE CRESTED DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1030, Value = "ICELANDIC SHEEPDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1031, Value = "BEAGLE HARRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1032, Value = "EURASIAN", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1033, Value = "DOGO ARGENTINO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1034, Value = "AUSTRALIAN KELPIE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1035, Value = "OTTERHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1036, Value = "HARRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1037, Value = "COLLIE SMOOTH", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1038, Value = "BORDER COLLIE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1039, Value = "ROMAGNA WATER DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1040, Value = "GERMAN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1041, Value = "BLACK AND TAN COONHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1042, Value = "AMERICAN WATER SPANIEL", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1043, Value = "IRISH GLEN OF IMAAL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1044, Value = "AMERICAN FOXHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1045, Value = "RUSSIAN-EUROPEAN LAIKA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1046, Value = "EAST SIBERIAN LAIKA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1047, Value = "WEST SIBERIAN LAIKA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1048, Value = "AZAWAKH", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1049, Value = "DUTCH SMOUSHOND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1050, Value = "SHAR PEI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1051, Value = "PERUVIAN HAIRLESS DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1052, Value = "SAARLOOS WOLFHOND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1053, Value = "NOVA SCOTIA DUCK TOLLING RETRIEVER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1054, Value = "DUTCH SCHAPENDOES", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1055, Value = "NEDERLANDSE KOOIKERHONDJE", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1056, Value = "BROHOLMER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1057, Value = "FRENCH WHITE AND ORANGE HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1058, Value = "KAI", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1059, Value = "KISHU", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1060, Value = "SHIKOKU", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1061, Value = "WIREHAIRED SLOVAKIAN POINTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1062, Value = "MAJORCA SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1063, Value = "GREAT ANGLO-FRENCH TRICOLOUR HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1064, Value = "GREAT ANGLO-FRENCH WHITE AND BLACK HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1065, Value = "GREAT ANGLO-FRENCH WHITE & ORANGE HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1066, Value = "MEDIUM-SIZED ANGLO-FRENCH HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1067, Value = "SOUTH RUSSIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1068, Value = "RUSSIAN BLACK TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1069, Value = "CAUCASIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1070, Value = "CANARIAN WARREN HOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1071, Value = "IRISH RED AND WHITE SETTER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1072, Value = "KANGAL SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1073, Value = "CZECHOSLOVAKIAN WOLFDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1074, Value = "POLISH GREYHOUND", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1075, Value = "KOREA JINDO DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1076, Value = "CENTRAL ASIA SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1077, Value = "SPANISH WATER DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1078, Value = "ITALIAN SHORT-HAIRED SEGUGIO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1079, Value = "THAI RIDGEBACK DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1080, Value = "PARSON RUSSELL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1081, Value = "SAINT MIGUEL CATTLE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1082, Value = "BRAZILIAN TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1083, Value = "AUSTRALIAN SHEPHERD", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1084, Value = "ITALIAN CANE CORSO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1085, Value = "AMERICAN AKITA", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1086, Value = "JACK RUSSELL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1087, Value = "DOGO CANARIO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1088, Value = "WHITE SWISS SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1089, Value = "TAIWAN DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1090, Value = "ROMANIAN MIORITIC SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1091, Value = "ROMANIAN CARPATHIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1092, Value = "AUSTRALIAN STUMPY TAIL CATTLE DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1093, Value = "RUSSIAN TOY", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1094, Value = "CIMARRÓN URUGUAYO", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1095, Value = "POLISH HUNTING DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1096, Value = "BOSNIAN AND HERZEGOVINIAN - CROATIAN SHEPHERD DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1097, Value = "DANISH-SWEDISH FARMDOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1098, Value = "ROMANIAN BUCOVINA SHEPHERD", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1099, Value = "THAI BANGKAEW DOG", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1100, Value = "MINIATURE BULL TERRIER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1101, Value = "LANCASHIRE HEELER", DatasetId = 3 },
                    new DefinedDatasetValue { Id = 1102, Value = "SEGUGIO MAREMMANO", DatasetId = 3 }
                );
        }
    }
}
